name: roi_assessment
version: "1.0.0"
config-version: 2

profile: roi_assessment

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

models:
  roi_assessment:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    analytics:
      +schema: analytics
      +materialized: view
    examples:
      +schema: examples
      +materialized: table

snapshots:
  roi_assessment:
    +target_schema: snapshots
